### ISSUE TITLE
The HTTP_EXTERNAL IP is visible inside index.html

### ISSUE THREAD

**Issue by mojovski** [Graylog2/graylog-docker#104]
I face a problem with the docker-compose configuration
```
- GRAYLOG_HTTP_EXTERNAL_URI=http://10.10.99.103:9000/
```
which makes the IP appear inside the index.html
```html
<body>
    <script src="http://10.10.99.103:9000/config.js"></script>
....
```

The problem is here, is that the graylog server is accessible from two different networks (it has two different IPs in different networks). If I access the server from network A, I see only IP IP_A, if I access the server from network B, I see it only via IP_B. Thus, if IP_A is 10.10.99.103, no one is able to access it from the network B.

I think a solution would be to remove the IP from the index.html and write
```html
<script src="/config.js"></script>
```
instead.

Can anyone advise how to achieve this?

Thank you very much!

**Comment by florianvolle** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
