### ISSUE TITLE
docker graylog root password is ?

### ISSUE THREAD

**Issue by lzhblog** [Graylog2/graylog-docker#105]
docker graylog root password is ?

**Comment by florianvolle** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!

**Comment by dbudakov** [comment]
login as root:
docker exec -u root -it [container_id] /bin/bash

**Comment by ShawHussain** [comment]
in kubernetes ?
