### ISSUE TITLE
arm64

### ISSUE THREAD

**Issue by zhongyong** [Graylog2/graylog-docker#106]
RUN   echo "export JAVA_HOME=/usr/local/openjdk-8"     > /etc/profile.d/graylog.sh &&   echo "export BUILD_DATE=${BUILD_DATE}"           >> /etc/profile.d/graylog.sh &&   echo "export GRAYLOG_VERSION=${GRAYLOG_VERSION}" >> /etc/profile.d/graylog.sh &&   echo "export GRAYLOG_SERVER_JAVA_OPTS='-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:NewRatio=1 -XX:MaxMetaspaceSize=256m -server -XX:+ResizeTLAB -XX:+UseConcMarkSweepGC -XX:+CMSConcurrentMTEnabled -XX:+CMSClassUnloadingEnabled -XX:+UseParNewGC -XX:-OmitStackTraceInFastThrow'" >> /etc/profile.d/graylog.sh &&   echo "export GRAYLOG_HOME=${GRAYLOG_HOME}"       >> /etc/profile.d/graylog.sh &&   echo "export GRAYLOG_USER=${GRAYLOG_USER}"       >> /etc/profile.d/graylog.sh &&   echo "export GRAYLOG_GROUP=${GRAYLOG_GROUP}"     >> /etc/profile.d/graylog.sh &&   echo "export GRAYLOG_UID=${GRAYLOG_UID}"         >> /etc/profile.d/graylog.sh &&   echo "export GRAYLOG_GID=${GRAYLOG_GID}"         >> /etc/profile.d/graylog.sh &&   echo "export PATH=${GRAYLOG_HOME}/bin:${PATH}"   >> /etc/profile.d/graylog.sh &&   apt-get update  > /dev/null &&   apt-get install --no-install-recommends --assume-yes     curl     tini     libcap2-bin     libglib2.0-0     fontconfig > /dev/null &&   addgroup     --gid "${GRAYLOG_GID}"     --quiet     "${GRAYLOG_GROUP}" &&   adduser     --disabled-password     --disabled-login     --gecos ''     --home ${GRAYLOG_HOME}     --uid "${GRAYLOG_UID}"     --gid "${GRAYLOG_GID}"     --quiet     "${GRAYLOG_USER}" &&   chown --recursive "${GRAYLOG_USER}":"${GRAYLOG_GROUP}" ${GRAYLOG_HOME} &&   setcap 'cap_net_bind_service=+ep' "${JAVA_HOME}/bin/java" &&   apt-get remove --assume-yes --purge     apt-utils > /dev/null &&   rm -f /etc/apt/sources.list.d/* &&   apt-get clean > /dev/null &&   apt autoremove --assume-yes > /dev/null &&   rm -rf     /tmp/*     /var/cache/debconf/*     /var/lib/apt/lists/*     /var/log/*     /usr/share/X11     /usr/share/doc/* 2> /dev/null

E: Unable to locate package tini

**Comment by jalogisch** [comment]
dear @zhongyong 

it would be very nice if you be a little more verbose in what you actually want to say. 

Would you like to use Graylog on arm64? Why do you run into this issue? Do you know why this happens? 

thank you

**Comment by jalogisch** [comment]
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.

**Comment by zhongyong** [comment]
set jvm path  ok
