### ISSUE TITLE
docker pull not working

### ISSUE THREAD

**Issue by e-volusian** [Graylog2/graylog-docker#115]
Hello, starting at this page https://hub.docker.com/r/graylog/graylog/ and trying to run `docker pull graylog/graylog` returns:

<pre>
$ docker pull graylog/graylog
Using default tag: latest
Error response from daemon: manifest for graylog/graylog:latest not found: manifest unknown: manifest unknown
</pre>

Trying to read the docs linked from hub.docker.com [returns 404](http://docs.graylog.org/en/stable/pages/installation/docker.html)

**Comment by jalogisch** [comment]
he @e-volusian 

this is not an error by Graylog. We have on purpose no `latest` tag. You always need to specify the Graylog version you want to have. 

But you are right that this might be not correct to have that command on the page - so I asked in the Docker Hub community for help how to remove that: https://forums.docker.com/t/change-docker-pull-command-on-page/89274

**Comment by e-volusian** [comment]
Thanks for your response. The question is answered.
