### ISSUE TITLE
config/graylog.conf should be updated

### ISSUE THREAD

**Issue by moafrancky** [Graylog2/graylog-docker#117]
Hi,

config/graylog.conf is rather old and sometimes misleading.

Ie: 'content_packs_auto_load' parameter should be replaced by 'content_packs_auto_install'

Kind regards.

**Comment by Oduig** [comment]
Cost me almost a day to figure out why my installation of Graylog was not working. Same thing: `content_packs_auto_load` is not supported by this version of Graylog, it should be `content_packs_auto_install`. There may be other config values which were changed in the meantime, that could cause problems when using this docker image.
