### ISSUE TITLE
Code 132 

### ISSUE THREAD

**Issue by thiagoloureiro** [Graylog2/graylog-docker#118]
I am trying to run the latest docker image for graylog 3.x and I can't make it work, I'm receiving Exit Code 132.

Red Hat Enterprise Linux 7.8

Some spec about the server:

For a workaround I'm using the Graylog 2.x
![MicrosoftTeams-image](https://user-images.githubusercontent.com/29433794/82327292-769cd300-99de-11ea-9d37-9d3821c7de57.png)
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/29433794/82327293-77ce0000-99de-11ea-84db-a494e0ea7e12.png)

**Comment by jalogisch** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
