### ISSUE TITLE
How to access to the Web Interface from another machine?

### ISSUE THREAD

**Issue by win32nipuh** [Graylog2/graylog-docker#122]
I have tried the 
      - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:9000/
and
      - GRAYLOG_HTTP_EXTERNAL_URI=http://localhost:9000/

In this case I can run the Web Interface in a browser on the local machine "mypc" the same where docker is running.
When I run http://mypc:9000 from another machine in the LAN I see an empty page"

How to fix it? to have access to the Graylog in docker from other machine in the LAN?

**Comment by jalogisch** [comment]
He @win32nipuh 

the `http_external_uri` need to be reachable by the Browser you want to access Graylog from - as the other machines localhost has no Graylog running this will not work. You need to put in there the machine where you run the docker container. 

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
