### ISSUE TITLE
Graylog docker image root password  & timezone problems

### ISSUE THREAD

**Issue by oguzhansrky** [Graylog2/graylog-docker#125]
Hi,

what I'm talking about is not web ui password.

A root user password is prompted for a Docker container

see steps;

1) docker exec -it graylog /bin/bash

2) su - root
Password:

here i am asking for user password here.

----------------------------------

I cannot update the time and date because there is no root user password.

**Comment by jalogisch** [comment]
he @oguzhansrky 

I have moved your question to the docker repo - but in addition I can give you the answer, we do not have a root password. 

If you need to change settings inside the image we recommend to build you own image based on ours. 

https://docs.graylog.org/en/3.3/pages/installation/docker.html#new-docker-image

**Comment by oguzhansrky** [comment]
he @jalogisch 

thank you for the info, this solved my problem for me.
