### ISSUE TITLE
Remove "latest" tag

### ISSUE THREAD

**Issue by joschi** [Graylog2/graylog-docker#13]
The "latest" tag in Docker doesn't provide any guarantees about which version of Graylog is being used which makes upgrades hard and infrastructure build unreliable.

This also invites users to (maybe unknowingly) use this anti-pattern.

Instead, we should only offer the specific versions of Graylog (`${GRAYLOG_VERSION}-${DOCKER_IMAGE_REVISION}`, e. g. `2.4.3-1`) and the "major" release (`${GRAYLOG_MAJOR}.${GRAYLOG_MINOR}`, e. g. `2.4`) as tags on Docker Hub.

For the latter we (kind of) guarantee non-breaking changes so that should be fine.

* http://container-solutions.com/docker-latest-confusion/
* https://medium.com/@mccode/the-misunderstood-docker-tag-latest-af3babfd6375
* http://blog.benhall.me.uk/2015/01/dockerfile-latest-tag-anti-pattern/
* https://developers.redhat.com/blog/2016/02/24/10-things-to-avoid-in-docker-containers/
* https://runnable.com/blog/9-common-dockerfile-mistakes

**Comment by joschi** [comment]
Up for discussion @Graylog2/engineers.

**Comment by mariussturm** [comment]
Poking through a couple of highly used images 9 out of 10 still have the latest tag. So if it doesn't create extra work I would keep the tag.

**Comment by jalogisch** [comment]
I personal think we should remove `latest` and but have the `${GRAYLOG_MAJOR}.${GRAYLOG_MINOR}` tag. 

This would make it far more easy and we will not destroy customer environments. As we have breaking changes we will see a high rise of complains once we released 3.0 and the `latest` tag docker image is updated.

**Comment by joschi** [comment]
I've removed the "latest" tag from [graylog/graylog](https://hub.docker.com/r/graylog/graylog/) and [graylog2/graylog](https://hub.docker.com/r/graylog2/graylog/).
