### ISSUE TITLE
Add support for mounting additional plugins

### ISSUE THREAD

**Issue by bernd** [Graylog2/graylog-docker#133]
Since Graylog 4.0 requires the new storage plugins to be present to start up correctly, we should introduce a mount point for adding additional plugins to the image.

Something like `-v /path/to/my/plugins:/plugins` or similar. The `docker-entrypoint.sh` script takes all plugins in `/plugins` and merges them with the default plugins we ship into a directory like `/plugins-merged`. The `/plugins-merged` would be the default `plugin_dir` in the container. Before merging the plugins we need to remove all plugins in `/plugins-merged` on startup to make sure there are no old plugins present.

This could be a workaround until https://github.com/Graylog2/graylog2-server/issues/6482 is implemented.

See: https://github.com/Graylog2/graylog2-server/issues/9521#issuecomment-730203573

**Comment by juju2112** [comment]
@bernd Once `plugins/` is mounted, everything that was in the directory before is gone (as far as the container is concerned). I think to do this, we'd need a third directory to store the default plugins, such as `/plugins-default`.

**Comment by bernd** [comment]
@juju2112 Yeah, agreed. That's what I tried to explain in the description. :smile:
