### ISSUE TITLE
Enterprise docker image isn't functional

### ISSUE THREAD

**Issue by asachs01** [Graylog2/graylog-docker#147]
When attempting to pull down the enterprise image from Dockerhub, the following error is presented:

```
$ docker pull graylog/graylog-enterprise:latest
Error response from daemon: manifest for graylog/graylog-enterprise:latest not found: manifest unknown: manifest unknown
```

After looking at Dockerhub, it looks like we don't have tags in place for this specific image, which may be causing the problem. CC @juju2112 .

**Comment by juju2112** [comment]
I think i remember being told we don't tag `latest` to keep from breaking people during upgrades. Paging @bernd to tell me if I remember correctly.

**Comment by asachs01** [comment]
Oh, I meant to mention that even w/out a tag, I end up seeing the same issue. I'll wait until Bernd's around.

**Comment by juju2112** [comment]
I see the problem. The Makefile overrides the variable that Dockerhub would normally use to determine the tag (I think).

https://github.com/Graylog2/graylog-docker/blob/4.0/Makefile#L8-L9

I'll see what I can do.

**Comment by juju2112** [comment]
Okay, I was wrong. The build is right, I just had to push a new tag to trigger a build.

@asachs01 Try this:

`docker pull graylog/graylog-enterprise:4.0.1-2`

**Comment by asachs01** [comment]
Will do! Thank @juju2112!

**Comment by juju2112** [comment]
@asachs01 Hey don't forget to test this!

**Comment by asachs01** [comment]
OH YEAH! It works, so g2g!
