### ISSUE TITLE
Graylog should wait for elasticsearch server

### ISSUE THREAD

**Issue by bendavis78** [Graylog2/graylog-docker#149]
Using the docker-compose examples from the [documentation](https://docs.graylog.org/en/4.0/pages/installation/docker.html#persisting-data) results in Graylog not being able to connect to elasticsearch, because elasticsearch sometimes takes a bit longer to start up.

The graylog entrypoint script should wait for the elasticsearch server before starting Graylog, otherwise the container will fail and exit.

As a workaround, I've resorted to using `sleep` in my docker-compose to give elasticsearch more time to start up:

```yaml
    entrypoint:
      - /bin/sh
      - -c
      - |
        sleep 30;
        /docker-entrypoint.sh
```

Note that `depends_on` is not enough to guarantee that the server is accepting connections. According to Docker docs, `depends_on` only determines the order in which containers are started. It waits until the container is **running** before starting the next, but that does not mean that the elasticsearch server is accepting connections yet.

**Comment by juju2112** [comment]
Yes, I ran into this, too. I'm adding the `wait-for-it` script onto the image to allow for it to be used to handle this.

**Comment by juju2112** [comment]
The [wait-for-it](https://github.com/vishnubob/wait-for-it) script is in the 4.0.2 image now. So you can set your entrypoint like this:

`entrypoint: /usr/bin/tini -- wait-for-it elasticsearch:9200 --  /docker-entrypoint.sh`

And it will wait for Elasticsearch to start up before starting Graylog.
