### ISSUE TITLE
URL in README gives config with old variable names

### ISSUE THREAD

**Issue by nmertins** [Graylog2/graylog-docker#15]
In the [Persist Log Data](https://github.com/Graylog2/graylog-docker#persist-log-data) section of the README, the `wget` command for downloading graylog.conf gives an older version of the config not compatible with Graylog 2.4 e.g. contains `elasticsearch_network_host` instead of `elasticsearch_hosts`. I think the correct URL is:

https://raw.githubusercontent.com/Graylog2/graylog-docker/2.4/config/graylog.conf

**Comment by joschi** [comment]
@nmertins Good catch. Thanks for reporting this!
