### ISSUE TITLE
 There is a node without any running inputs.

### ISSUE THREAD

**Issue by zengxc-1996** [Graylog2/graylog-docker#161]
I tried to go in to the Graylog server via docker-compose file, and it showed that everything was OK, but there was a warning. I want to know how to solve this problem.

![image](https://user-images.githubusercontent.com/63622990/114682740-f2fc7b00-9d41-11eb-964c-f1fb03444498.png)

Thanks for your help, please leave me a message.

**Comment by bernd** [comment]
@zengxc-1996 This message will disappear once you start your first Graylog inputs on "System / Inputs".
