### ISSUE TITLE
Include the integration plugins in the docker image 

### ISSUE THREAD

**Issue by kaiomatico** [Graylog2/graylog-docker#165]
Hi :-),
I recently wanted to configure slack alerts / notifications, but the notification plugin did not show up. After some research I found this thread which tells that the "integrations" plugin is needed for slack notifications: https://community.graylog.org/t/graylog-4-0-cant-add-slack-notification/17925/5 .  
So after downloading and extracting https://downloads.graylog.org/releases/graylog-integrations/graylog-integrations-plugins-4.0.8.tgz to `/usr/share/graylog/plugin/graylog-plugin-integrations-4.0.8.jar` and restarting the container I could select and send slack notifications.
I think this plugin should be included in the docker image by default or at least this should be documented that it is missing, or is there any reason not to do this?

Thank you

**Comment by bernd** [comment]
Done in #166.

**Comment by juju2112** [comment]
Thanks for asking us about it, @kaiomatico!
