### ISSUE TITLE
How to change admin password?

### ISSUE THREAD

**Issue by stepanselyuk** [Graylog2/graylog-docker#167]
Hello,

I tried to change the admin password using the env variable GRAYLOG_ROOT_PASSWORD_SHA2 with a new sha2 hash. Then I restarted the pod and still cannot log in.

```
[graylog-0 graylog-server]  2021-07-10 11:43:17,682 INFO    [SessionCreator] - Invalid credentials in session create request. Actor: "urn:graylog:user:admin" - {}
```

Also, I was not able to find `server.conf` in the docker image file system.

**Comment by juju2112** [comment]
I think the config file you're looking for is here:

```
donald@laptop:~/src/ci-infrastructure/ansible$ docker run -it --entrypoint /bin/sh graylog/graylog:4.1 
$ ls -l /usr/share/graylog/data/config/graylog.conf
-rw-r--r-- 1 graylog graylog 33914 Jun 23 15:31 /usr/share/graylog/data/config/graylog.conf
```

I'm not sure about the password, What command are you using to create the hash?

**Comment by asachs01** [comment]
@stepanselyuk hi there. We use Github for tracking issues with Graylog and for this repo, specifically issues with our Docker image. This doesn't appear to be an actual issue with the image itself. Please open a post in the [Graylog Community](https://community.graylog.org/) and someone there will be able to help.
