### ISSUE TITLE
Elasticsearch heap size in README seems small

### ISSUE THREAD

**Issue by nmertins** [Graylog2/graylog-docker#18]
Elasticsearch says in their own documentation that the default heap size of 1 GB is likely too small. Yet in the example compose config in the README it's set even lower at 512 MB. Consider increasing to match Elasticsearch's recommendations.

https://www.elastic.co/guide/en/elasticsearch/guide/current/heap-sizing.html

**Comment by joschi** [comment]
@nmertins The configuration in the README.md is just an example and not a recommendation to use for production. It works perfectly well as an example for a minimal amount of messages.

Your production setup has to be customized for your particular use case and your requirements.
