### ISSUE TITLE
Integration test fails with docker-compose 2.x

### ISSUE THREAD

**Issue by supahgreg** [Graylog2/graylog-docker#188]
It looks like the `.env` isn't being picked up when `test/integration_test.sh` runs with `docker-compose` on `2.x`.  Dropping back to `1.x` gets things running again.

Ubuntu 21.10
Docker 20.10.10
`graylog-docker` @ 9bd5687b94dda1edffd476e093492105b5d9d6be

**Comment by malcyon** [comment]
Do you mean `docker-compose` v2.x? I didn't even know that was out.

**Comment by malcyon** [comment]
Ah, obviously from the title. I just read it poorly.

**Comment by supahgreg** [comment]
Yep-- and definitely not a big deal since `2.x` is still a bit rough.  I can do some poking around later on to see what's going on.

**Comment by supahgreg** [comment]
I'm no longer seeing this with Docker Compose `2.6` and Docker `20.10.17`.  Closing...
