### ISSUE TITLE
problem in access to gray log from graypy python code

### ISSUE THREAD

**Issue by EhsanSaZ** [Graylog2/graylog-docker#20]
i installed graylog docker on  my pc.
i cant log in to it with python graypy module and also cant get access to webinterface of graylog from another pc in the same network with the first one.
here is the error

> We are experiencing problems connecting to the Graylog server running on http://0.0.0.0:9000/api. Please verify that the server is healthy and working correctly.
You will be automatically redirected to the previous page once we can connect to the server.

Do you need a hand? We can help you.
Less details
This is the last response we received from the server:

Error message
Request has been terminated
Possible causes: the network is offline, Origin is not allowed by Access-Control-Allow-Origin, the page is being unloaded, etc.
Original Request
GET http://0.0.0.0:9000/api/system/sessions
Status code
undefined
Full error message
Error: Request has been terminated
Possible causes: the network is offline, Origin is not allowed by Access-Control-Allow-Origin, the page is being unloaded, etc.

**Comment by joschi** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
