### ISSUE TITLE
README on Docker Hub is dependent upon last version built

### ISSUE THREAD

**Issue by coffee-squirrel** [Graylog2/graylog-docker#202]
Currently `4.1.11` is shown as the latest release in the README contents @ https://hub.docker.com/r/graylog/graylog and https://hub.docker.com/r/graylog/graylog-enterprise/ since it was built after `4.2.5`.  This will eventually get sorted out when a `4.3.0` or `4.2.6` lands, but in the meantime a user looking at Docker Hub might get a bit confused.

**edit:**  Hm, now both show `4.2.5`.  Manual correction?  Either way, this isn't a big deal but might be worth keeping in mind w/ the release process.

![image](https://user-images.githubusercontent.com/19417721/148282927-42b924df-dcfe-4676-ace5-42e3e8690369.png)

**Comment by malcyon** [comment]
Yeah, I fixed it. It's just because I ran the 4.1 release after I did the 4.2 release. I guess Docker Hub pulls the README from whatever latest branch gets commits?
