### ISSUE TITLE
Rebuild dopcker image against more recent java

### ISSUE THREAD

**Issue by pastukhov** [Graylog2/graylog-docker#24]
Hello!
Since 1.8.0_131 openjdk support  UseCGroupMemoryLimitForHeap  option, but graylog2/server:2.4.5-1 builded against old java for now.

Please trigger a rebuild docker image to fix it.

P.S.

I found 2 repos:
https://hub.docker.com/u/graylog/
and https://hub.docker.com/u/graylog2/

Whai should i use?

**Comment by joschi** [comment]
@pastukhov Please use the correct image: https://hub.docker.com/r/graylog/graylog/
