### ISSUE TITLE
Unidentified file in /usr/bin. malware ?

### ISSUE THREAD

**Issue by mnsmithuk** [Graylog2/graylog-docker#280]
In the Graylog 6.1 docker image (docker image id 1c4445a79789), there is a binary file in /usr/bin called '['.

What is this ?

**Comment by coffee-squirrel** [comment]
https://www.google.com/search?q=linux+square+bracket+command+%2Fusr%2Fbin

**Comment by mnsmithuk** [comment]
Not sure why i didnt realise this before.  Thanks.
