### ISSUE TITLE
GRAYLOG_SERVER_JAVA_OPTS default settings

### ISSUE THREAD

**Issue by hangstl** [Graylog2/graylog-docker#35]
Might this be an issue with the default GRAYLOG_SERVER_JAVA_OPTS settings?
https://blogs.oracle.com/java-platform-group/java-se-support-for-docker-cpu-and-memory-limits

**Comment by runningman84** [comment]
Does the current docker image respect the cgroup settings and does not need any Xms setting in JAVA_OPTS?

**Comment by vaizki** [comment]
I am running 3.0.2 and can see the JVM started with these flags:
```
-XX:+UnlockExperimentalVMOptions 
*-XX:+UseCGroupMemoryLimitForHeap *
-XX:NewRatio=1 
-XX:MaxMetaspaceSize=256m 
-server 
-XX:+ResizeTLAB 
-XX:+UseConcMarkSweepGC 
-XX:+CMSConcurrentMTEnabled 
-XX:+CMSClassUnloadingEnabled 
-XX:+UseParNewGC 
-XX:-OmitStackTraceInFastThrow -jar 
-Dlog4j.configurationFile=/usr/share/graylog/data/config/log4j2.xml 
-Djava.library.path=/usr/share/graylog/lib/sigar/ 
-Dgraylog2.installation_source=docker
```

If I set the memory limit for the container to 2GB, I get a max heap size of 486.4MB so it is respecting the container cgroup limits but being very wasteful. The machine has 64GB of RAM.

With Java 10, the JVM by default respects container limits by default and has much nicer tunables... wink wink.

**Comment by juju2112** [comment]
Just doing some testing, it seems like it does respect the cgroup settings. If you limit the amount of RAM available to the container, the JVM will start with less RAM. But if you don't limit it, it uses what the underlying OS has available.
