### ISSUE TITLE
The entrypoint runs as root, should run as graylog

### ISSUE THREAD

**Issue by chrispoupart** [Graylog2/graylog-docker#36]
Multi-tenant Kubernetes services such as OpenShift do not allow containers to run as root, and as such, the Graylog image fails to run on OpenShift.

It looks like you already create the greylog user, and change the file ownership to graylog.  All that would be left to do is a `USER graylog` entry in the Dockerfile.

**Comment by jalogisch** [comment]
This has now merged onto the 2.4 and 2.5 branch and only need to be added to the 3.0 branch.

**Comment by jalogisch** [comment]
all images are now updated.
