### ISSUE TITLE
Running in Openshift

### ISSUE THREAD

**Issue by mbialitskiy** [Graylog2/graylog-docker#38]
Hi! 
I'm trying to run docker image of Graylog (3.0, 2.4.6-1) in Openshift. The creation of pod fails with error:

 `/docker-entrypoint.sh: line 35: exec: graylog: not found`

Any ideas why it could be?

**Comment by spepe91** [comment]
I receive the same error :(

**Comment by jalogisch** [comment]
we do not have an openshift environment to test this - we would need someone from the community to look into this.

**Comment by chrispoupart** [comment]
@jalogisch There are a few options for testing, but the easiest would be [minishift](https://github.com/minishift/minishift) or a free account on [openshift.com](https://www.openshift.com/learn/get-started/).

That being said, I think that yes, it is likely related to the issue I raised in #36.  I unfortunately have not had time to come back to that one.  Hopefully sometime in the near future I can do some testing and provide a PR for you.

**Comment by runningman84** [comment]
https://github.com/Graylog2/graylog-docker/pull/55 will also help for openshift deployments...

**Comment by jalogisch** [comment]
as soon as the new builds are published we would need you to check them again. This will happen in the next hours.

If that problem is still persistent, please re-open the issue with more details.
