### ISSUE TITLE
Error in the ReadMe file for the setup steps

### ISSUE THREAD

**Issue by PaulDMendoza** [Graylog2/graylog-docker#4]
There is a missing dash (-) in the readme for getting the elasticsearch container running I think. If I look at the logs for the command, I see this error.

![image](https://user-images.githubusercontent.com/1039795/28932333-f8d06858-782d-11e7-8ca9-b84db232d0db.png)

So I added an extra dash and it seems to start the cluster now and everything works okay. I'm on Windows using Powershell btw.

docker run --name some-elasticsearch -d elasticsearch:2 elasticsearch --Des.cluster.name="graylog"

**Comment by joschi** [comment]
@PaulDMendoza The examples in the README have been updated in d68b8a1f73e64895a5be7816ce4ee74602168142.
