### ISSUE TITLE
Permission denied on docker-compose up

### ISSUE THREAD

**Issue by tacone** [Graylog2/graylog-docker#41]
I've tried to run graylog with docker-compose using the example found in readme.md and got this:

```
$ docker-compose up
WARNING: Some services (elasticsearch) use the 'deploy' key, which will be ignored. Compose does not support 'deploy' configuration - use `docker stack deploy` to deploy to a swarm.
Starting graylog-docker_elasticsearch_1 ... done
Starting graylog-docker_mongo_1         ... done
Starting graylog-docker_graylog_1       ... done
Attaching to graylog-docker_elasticsearch_1, graylog-docker_mongo_1, graylog-docker_graylog_1
elasticsearch_1  | [2018-10-08T15:48:17,028][INFO ][o.e.n.Node               ] [] initializing ...
mongo_1          | error: exec: "/usr/local/bin/docker-entrypoint.sh": stat /usr/local/bin/docker-entrypoint.sh: permission denied
graylog_1        | error: exec: "/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java": stat /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java: permission denied
```
Mongo and graylog containers fail with permission denied, while elasticsearch boots just fine.

Any hints?

**edit:** additional information

host: Ubuntu 18.04.1 LTS
docker version: Docker version 18.06.1-ce, build e68fc7a
docker-compose version: docker-compose version 1.21.2, build a133471

**Comment by jalogisch** [comment]
the docker-compose example wasn't well tested and reverted to the previous version with https://github.com/Graylog2/graylog-docker/commit/0c620639535652d50e1ba352976adfba4d09e279 that now should work again
