### ISSUE TITLE
"curl: (52) Empty reply from server" when posting GELF message

### ISSUE THREAD

**Issue by activebiz** [Graylog2/graylog-docker#46]
Hi,

I have got docker setup using docker-compose from https://github.com/Graylog2/graylog-docker. 

The Graylog server is up and running (web interface). However when I try to post log using following I get "curl: (52) Empty reply from server".

curl -X POST -H 'Content-Type: application/json' -d '{ "version": "1.1", "host": "example.org", "short_message": "A short message", "level": 5, "_some_info": "foo" }' 'http://localhost:12201/gelf'

Any idea?

Thanks

**Comment by jalogisch** [comment]
Did you setup the HTTP GELF Input?

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
