### ISSUE TITLE
Install own plugins by default and enable with env

### ISSUE THREAD

**Issue by runningman84** [Graylog2/graylog-docker#47]
Right now you have to build a own docker image if you want to use plugins like prometheus... 

It would be cool to have them included by default and enabled via an env variable.

**Comment by pastukhov** [comment]
Sounds good

**Comment by jalogisch** [comment]
The easiest way would be to include them via mounted volumes. Like described in the documentation: http://docs.graylog.org/en/2.4/pages/installation/docker.html#volume-mounted-plugin

Official shipped plugins will be always included in the Docker Image.

**Comment by runningman84** [comment]
The Prometheus Export is an official plugin and therefore included by default?

**Comment by runningman84** [comment]
In order to make things easier in kubernetes deployments it would be cool if graylog would just read additional plugins form a secondary location. This would allow us to just download them in a init container and use the official image.
