### ISSUE TITLE
The "GRAYLOG_ELASTICSEARCH_HOSTS" variable is not supported

### ISSUE THREAD

**Issue by aliasmee** [Graylog2/graylog-docker#5]
hi, I found the latest version of the docker image graylog.conf is still very old.

Is this unsupported? If this is the case, please mark the instructions on the document.
At the moment I am going to build the entire graylog cluster on kubernetes, using mongo3, elasticsearch5.5. However, this latest version of the mirror, there are a lot of variables on the es cluster are not supported. Help me! Thanks

**Comment by joschi** [comment]
> I found the latest version of the docker image graylog.conf is still very old.

Which one is that specifically?

**Comment by aliasmee** [comment]
'elasticsearch_hosts'
Refer to: [](http://docs.graylog.org/en/stable/pages/configuration/elasticsearch.html)
I created the container using the latest graylog-2.3.1 image and went into the container to see the graylog.conf file. Compared to the official website, there was a lot of parameter configuration items missing

**Comment by joschi** [comment]
@aliasmee Feel free to use your own custom Graylog configuration file, but the configuration file distributed with the [graylog2/graylog](https://hub.docker.com/r/graylog2/graylog/) (or [graylog/graylog](https://hub.docker.com/r/graylog/graylog/)) Docker image is up to date and working.

https://github.com/Graylog2/graylog-docker/blob/2.3.0-1/config/graylog.conf#L175-L181

**Comment by aliasmee** [comment]
According to your prompt, I found the correct image version. thank you very much. Now that they have worked, I am now testing the high availability of the entire cluster. If there are other problems, I will bother you again. ... ^ _ ^
