### ISSUE TITLE
Healthcheck script will fail if the container is attached to multiple networks

### ISSUE THREAD

**Issue by Sryther** [Graylog2/graylog-docker#57]
Hello everyone,

I recently updated my Graylog using the image `graylog/graylog:2.5.1-2`. Before, I was using the image `graylog2/server:2.4.3-1`.

After the update, the server is running properly but after serveral minutes (2 minutes to be exact), the container is considered as unhealthy. So I tried to debug the [`health_check.sh`](https://github.com/Graylog2/graylog-docker/blob/2.5/health_check.sh) script. All seemed to be ok until I tried to see which value was behind the [`${host}`](https://github.com/Graylog2/graylog-docker/blob/2.5/health_check.sh#L26) variable in the script.

`${host}` was equal to this: `10.7.0.97 10.117.0.105`.
This value is computed with the following: [`host="$(hostname -i || echo '127.0.0.1')"`](https://github.com/Graylog2/graylog-docker/blob/2.5/health_check.sh#L5).

My conclusion is that the command `hostname -i` returns multiple values if the container is attached to multiple networks. In that way, the HEALTHCHECK was always in error, and the container would restart.

I didn't want to create any PR before knowing what solution should be the best for this case. Should the script take the first host found (but maybe it's too ambigous) or always `127.0.0.1`? Actually, I don't see the cases where the real IP is relevant instead of `127.0.0.1`.

Anyway, I'll take your opinion first 🙂

**Comment by jalogisch** [comment]
When thinking about that, the current health_check is not working correctly.

It should simply take `GRAYLOG_REST_LISTEN_URI` and only if that is set to `0.0.0.0` it can take localhost or one of the possible returns of `hostname --all-ip-addresses`.

> Actually, I don't see the cases where the real IP is relevant instead of 127.0.0.1.

Imagine you build a complete Stack inside a Docker network and you bind your REST Interface to one Interface (and not all) then it might happen that the check on `127.0.0.1` will fail because nothing is listening.

**Comment by jam49** [comment]
as a further side; i dont see how these will work either in the script
# rest_listen_uri = http://0.0.0.0:9000/api/
rest_listen_uri=$(grep "rest_listen_uri" ${GRAYLOG_HOME}/data/config/graylog.conf)
#rest_enable_tls = true
tls=$(grep "^rest_enable_tls" ${GRAYLOG_HOME}/data/config/graylog.conf | awk -F '=' '{print $2}' | awk '{$1=$1};1')

Both the values could be set via ENV variables for the docker, and not specificed in the conf.

You need to create the health check dynamically in the docker entry point.

**Comment by shumbashi** [comment]
The only way I found to work around the multiple networks issue is to override the health check in docker-compose file.
`
  healthcheck:
      test: ["CMD", "curl", "--silent", "-f", "http://127.0.0.1:9000/api"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 40s
`

**Comment by jalogisch** [comment]
The solution would be not only to select the port from the variable:

https://github.com/Graylog2/graylog-docker/blob/fd8da8c1f50f0760279dd1f4355f8816be656735/health_check.sh#L18-L24

But to get the host/ip too from the variables that should be the smartest solution I can imagine.
