### ISSUE TITLE
fails with read only mapped volumes

### ISSUE THREAD

**Issue by Shohou** [Graylog2/graylog-docker#58]
docker-entrypoint.sh has this line:
`chown --recursive "${GRAYLOG_USER}":"${GRAYLOG_GROUP}" "${GRAYLOG_HOME}/data"`

It fails if I add files under data as read only volumes from the host. If I make them writable (which I don't like anyway) it changes owner and causes other troubles for me.

It would be nice to ignore this error when chown can't change owner. Please consider changing this line to
`chown --recursive "${GRAYLOG_USER}":"${GRAYLOG_GROUP}" "${GRAYLOG_HOME}/data" || true`

**Comment by jalogisch** [comment]
The mapped volumes need to be read/write for the Graylog user as the journal is stored in this location.

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!

**Comment by Shohou** [comment]
I guess journal is stored at some specific location under data directory, so not everything under data directory has to be writable. If I map as a volume some data/contentpacks/blabla.json does it need to be writable?

I don't ask to remove that line, I ask not to fail completely

**Comment by Shohou** [comment]
or well, add another line which chowns data/journal separately and fail there if it is not writable
