### ISSUE TITLE
Error running graylog server on kubernetes environment (/w configmap)

### ISSUE THREAD

**Issue by onesolpark** [Graylog2/graylog-docker#62]
Hello everyone,
There is an issue with running graylog on kubernetes environment by using graylog.conf as a configmap.

The main issue is due to the chown command in docker-entrypoint.sh
`chown --recursive "${GRAYLOG_USER}":"${GRAYLOG_GROUP}" "${GRAYLOG_HOME}/data"`

configmaps are mounted as readonly volumes into the container which makes the command above to break.

As a workaround I've changed the entry point to below and there weren't any issues running graylog (for the past month).
`chown --recursive "${GRAYLOG_USER}":"${GRAYLOG_GROUP}" "${GRAYLOG_HOME}/data" || echo "Skipping chown command"`

The question is, are there any issues regarding skipping the chown command?
And are there any other workarounds that you can think of?

**Comment by pastukhov** [comment]
Just FYI
Every config parameter in graylog.conf can be customized with env var capitalised and  with GRAYLOG_ prefix.
https://github.com/Graylog2/graylog2-images/issues/55

**Comment by onesolpark** [comment]
> Just FYI
> Every config parameter in graylog.conf can be customized with env var capitalized and with GRAYLOG_ prefix.
> [Graylog2/graylog2-images#55](https://github.com/Graylog2/graylog2-images/issues/55)

Thanks, that could be an option.
Except that we have at least 20 options we have to put in (Email, rest api ...) 
and that would really make deployment yaml confusing..
But again thanks for updating on the environment variable option

**Comment by avoinea** [comment]
This is actually a blocker for me as the container won't start if you declare journal as a volume

```
   ...
    volumes:
    - logcentral-data:/usr/share/graylog/data/journal
```

Errorlog:
```
2/15/2019 12:32:38 PM adding environment opts
2/15/2019 12:32:38 PM chown: changing ownership of '/usr/share/graylog/data/journal': Operation not permitted
```

Usually you can't use chown with Dockerfile USER directive: 
https://github.com/Graylog2/graylog-docker/blob/b976b35857590d2fb946fb608faf568f8a277b39/docker-entrypoint.sh#L51

https://github.com/Graylog2/graylog-docker/blob/b976b35857590d2fb946fb608faf568f8a277b39/Dockerfile#L125

**Comment by pastukhov** [comment]
Faced same issue, but while mounting configmap with content pack.

**Comment by artturik** [comment]
Same issue here,
Commit that changed behaivour that was working on Graylog 2.5 -
https://github.com/Graylog2/graylog-docker/commit/d076509dd9cea83abc3eedd2b88a2f695d33e169#diff-60713fb19f6c50a2473835df63ff17f9L19

As temporary solution changed at `docker-entrypoint.sh` `setup` function to

```bash    
setup() {
      # Create data directories
      for d in journal log plugin config contentpacks
      do
        dir=${GRAYLOG_HOME}/data/${d}
        [[ -d "${dir}" ]] || mkdir -p "${dir}"
        if [[ "$(stat --format='%U:%G' $dir)" != 'graylog:graylog' ]] && [[ -w "$dir" ]]; then
          chown -R graylog:graylog "$dir" || echo "Warning can not change owner to graylog:graylog"
        fi
      done
 }
```

**Comment by jalogisch** [comment]
@artturik would you like to submit a PR for your proposed change?

**Comment by onesolpark** [comment]
The changes I made is very similar to the changes above
```
${GRAYLOG_HOME}/data" || echo "Skipping chown command"
```
@jalogisch The question I have is, does skipping chown for specific files have any sideeffects?

**Comment by jalogisch** [comment]
the `journal` and `log` folder need to be writable by the Graylog user - the others need to be readable. 

As long as the above rules becomes true no sideeffects.

**Comment by artturik** [comment]
@pastukhov just realized that contentpacks autoload was removed from graylog 3.0 - https://github.com/Graylog2/graylog2-server/pull/5070

@jalogisch - sure, will submit PR

**Comment by pastukhov** [comment]
It should be more gently
For example check mounts inside $GRAYLOG_HOME for RO and skip chown
I will made PR ASAP

**Comment by artturik** [comment]
@pastukhov it already checks if folder is writable for current user -
```bash
[[ -w "$dir" ]]
```
https://github.com/Graylog2/graylog-docker/blob/3.0/docker-entrypoint.sh#L50

**Comment by pastukhov** [comment]
Yep, but i faced with case when the folder is writable itself, but files inside are belonging to root and not writable
