### ISSUE TITLE
healthcheck failed

### ISSUE THREAD

**Issue by bodsch** [Graylog2/graylog-docker#71]
With configured `GRAYLOG_HTTP_EXTERNAL_URI=http://0.0.0.0:9000/` the healthcheck will fail.
A possible solution would be to parse the IP in the healtheck script and replace `0.0.0.0.0` with `127.0.0.1`

**Comment by jalogisch** [comment]
but `GRAYLOG_HTTP_EXTERNAL_URI` is never used in the script ... so it defaults back to 127.0.0.1 ...

**Comment by bodsch** [comment]
you are right.
thats my mistake and an older configuration in my test environment.
