### ISSUE TITLE
Docker "--link" flag is deprecated, may eventually be removed, switch to user-defined networks

### ISSUE THREAD

**Issue by loganmarchione** [Graylog2/graylog-docker#74]
See this link for more details:
https://docs.docker.com/compose/compose-file/#links

> Warning: The --link flag is a legacy feature of Docker. It may eventually be removed. Unless you absolutely need to continue using it, we recommend that you use user-defined networks to facilitate communication between two containers instead of using --link. One feature that user-defined networks do not support that you can do with --link is sharing environmental variables between containers. However, you can use other mechanisms such as volumes to share environment variables between containers in a more controlled way.

The current docker-compose.yml example references this feature. Can the compose file be updated to use user-defined networks instead of links?
```
    links:
      - mongodb:mongo
      - elasticsearch
```

**Comment by mbrucher** [comment]
Seem like this fundamental issue doesn't bother greylog people. Is the product even maintained?

**Comment by jalogisch** [comment]
@mbrucher please calm down and take care of your voice. 

You might have a different idea how many we are and what we do. In addition this is an open source product and if you have the knowledge to contribute and participate - you are very welcome.

**Comment by bodsch** [comment]
> See this link for more details:
> https://docs.docker.com/compose/compose-file/#links
> 
> The current docker-compose.yml example references this feature. Can the compose file be updated to use user-defined networks instead of links?

The created docker-compose file supports version 2, where the link attribute is still supported.
But you are welcome to provide a new compatible docker-compose file.

**Comment by jalogisch** [comment]
the above merged PR to the documentation fixed this.
