### ISSUE TITLE
Trying to build my own docker image for Graylog.

### ISSUE THREAD

**Issue by iukea1** [Graylog2/graylog-docker#75]
Hello,

I am trying to build a docker image off this repo, but I keep on getting the following error. 

Can you guys give me a bump in the right direction? 

```
 ---> Running in 6798259d12ee
sha256sum: graylog-.tgz.sha256.txt: no properly formatted SHA256 checksum lines found
The command '/bin/sh -c sha256sum --check "graylog-${GRAYLOG_VERSION}.tgz.sha256.txt"' returned a non-zero code: 1
```

**Comment by jalogisch** [comment]
You do not have a Version for Graylog set. Means, Docker can't download anything as it does not know what.

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!

**Comment by saber13812002** [comment]
how can i set version in my docker file?
