### ISSUE TITLE
No Graylog 3.0.2 image available

### ISSUE THREAD

**Issue by ntimo** [Graylog2/graylog-docker#79]
Hello,
the readme.md mentions that the 3.0 tag should contain Graylog 3.0.2 but it contains Graylog 3.0.2 also the tag 3.0.2-1 does not exist. Does this have a reason? And also when are the Graylog 3.0.2 images going to be available?

Thanks,
Timo

**Comment by jalogisch** [comment]
he @ntimo we fixed that issue. After the Docker Security issue the automated builds got disabled and we need to enable that chain again. Thank you for raising the issue.
