### ISSUE TITLE
Please document GRAYLOG_ELASTICSEARCH_HOSTS

### ISSUE THREAD

**Issue by runningman84** [Graylog2/graylog-docker#8]
I found some pages who are refering GRAYLOG_ELASTICSEARCH_HOSTS but I haven't found anything here.

**Comment by joschi** [comment]
@runningman84 The `GRAYLOG_ELASTICSEARCH_HOSTS` environment variable translates to the `elasticsearch_hosts` setting in the Graylog configuration file:
https://github.com/Graylog2/graylog2-server/blob/9f2c6ef5c1c0f8b77e73d1298d57c7223087eedf/misc/graylog.conf#L172-L178

You can override any configuration setting from the Graylog configuration file with an environment variable of the the same name with the prefix "GRAYLOG_" and all upper case, e. g. you can override `is_master` with the `GRAYLOG_IS_MASTER` environment variable.

This is also described in the documentation at http://docs.graylog.org/en/2.3/pages/installation/docker.html#configuration

**Comment by runningman84** [comment]
yes, but it is not documented on this page and therefore not documented at the Docker Hub:
https://hub.docker.com/r/graylog2/server/

**Comment by joschi** [comment]
@runningman84 It's documented in the "Configuration" section of the README you've linked to: https://hub.docker.com/r/graylog2/server/

<img width="892" alt="graylog2/server image README" src="https://user-images.githubusercontent.com/43951/30473341-68fba2b6-9a00-11e7-91a5-105aab77f218.png">
