### ISSUE TITLE
Environment variables not overriding default configuration

### ISSUE THREAD

**Issue by mud5150** [Graylog2/graylog-docker#80]
`GRAYLOG_MONGODB_URI` and `GRAYOG_ELASTICSEARCH_HOSTS` environment variables are not working. I have `"mongodb://graylog:fakepassword@10.x.x.x:27017/graylog"` defined as the environment variable. Similarly an ip is being passed in for the elasticsearch host.  I have exec'd into the container and can verify these are set correctly. I'm getting host name lookup failures in the logs looking up the default names e.g. `Caused by: java.net.UnknownHostException: elasticsearch`

I'm pulling tag `3.0.2`

**Comment by jalogisch** [comment]
@mud5150 would you mind sharing your configuration? I can't see the issue in my setup and I guess it might have something todo with your environment. So I would need to have your configuration to check if that might be the reason.

**Comment by vaizki** [comment]
Works For Me .. I just set up GL 3.0.2 (pulled an hour ago) in Kubernetes today and I am overriding both of those settings via environment variables. I am having no issues.

**Comment by jalogisch** [comment]
no feedback from the issue opener, so I'll close that now.
