### ISSUE TITLE
Environmental Variable GRAYLOG_TRANSPORT_EMAIL_FROM_EMAIL Not Overriding Config

### ISSUE THREAD

**Issue by rnunley** [Graylog2/graylog-docker#81]
Overriding Docker environment variables is working for all but GRAYLOG_TRANSPORT_EMAIL_FROM_EMAILwhen using image graylog/graylog:3.0. The value is always the default value of graylog@example.com regardless of the value set.

**Comment by jalogisch** [comment]
Does you refer what is visible in the UI if you define an alert? If yes, that one is just a template and more a bug in the server code that the server does not take the configured mail from.

**Comment by jalogisch** [comment]
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.
