### ISSUE TITLE
Deployment failed. no properly formatted SHA256 checksum lines found

### ISSUE THREAD

**Issue by saber13812002** [Graylog2/graylog-docker#83]
Step 1/32 : FROM debian:stretch-slim as graylog-downloader
 ---> 49ec158b9895
Step 2/32 : ARG VCS_REF
 ---> Using cache
 ---> e000f2960cbb
Step 3/32 : ARG GRAYLOG_VERSION
 ---> Using cache
 ---> e9ede2ef3368
Step 4/32 : WORKDIR /tmp
 ---> Using cache
 ---> 4ab5b6c9217b
Step 5/32 : RUN   apt-get update  > /dev/null &&   apt-get install --assume-yes     ca-certificates     curl > /dev/null
 ---> Using cache
 ---> 3bf58b6046d3
Step 6/32 : RUN   curl     --silent     --location     --retry 3     --output "/tmp/graylog-${GRAYLOG_VERSION}.tgz"     "http
 ---> Using cache
 ---> f9387ec8135a
Step 7/32 : RUN   curl     --silent     --location     --retry 3     --output "/tmp/graylog-${GRAYLOG_VERSION}.tgz.sha256.txt"     "https://packages.graylog2.org/releases/graylog/graylog-${GRAYLOG_VERSION}.tgz.sha256.txt"
 ---> Using cache
 ---> 04e7495b7e4b
Step 8/32 : RUN   sha256sum --check "graylog-${GRAYLOG_VERSION}.tgz.sha256.txt"
 ---> Running in 59e0ff891268

sha256sum: graylog-.tgz.sha256.txt: no properly formatted SHA256 checksum lines found
The command '/bin/sh -c sha256sum --check "graylog-${GRAYLOG_VERSION}.tgz.sha256.txt"' returned a non-zero code: 1

 »   Error: Deployment failed.

how can i set my graylog version please help me

**Comment by jalogisch** [comment]
It looks like you used the dockerfile to create your own docker image. It looks like you did not use the provided `make` method. If so you should look how we call the docker build in https://github.com/Graylog2/graylog-docker/blob/3.0/hooks/build that also shows how we set the version. 

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!

**Comment by ssh30** [comment]
sed -i 's/${GRAYLOG_VERSION}/put_here_the_version_you_are_using/g' Dockerfile

example
sed -i 's/${GRAYLOG_VERSION}/3.3.5/g' Dockerfile
