### ISSUE TITLE
docker-compose.yml start graylog.The custom port does not take effect 

### ISSUE THREAD

**Issue by kildee** [Graylog2/graylog-docker#84]
Use docker-compose.yml start graylog.I want to use port 9400 as port graylog, but use docker start graylog ，the port don't take effect,and port 9000 can't access.My configuration is as follows.May I ask if I made a configuration error?Thank you
![image](https://user-images.githubusercontent.com/26431033/60820820-d6c6c400-a1d4-11e9-8eaf-d1aea73c41da.png)

**Comment by jalogisch** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
