### ISSUE TITLE
"official library" image

### ISSUE THREAD

**Issue by J0WI** [Graylog2/graylog-docker#90]
Are there any plans to push this image to the standard library?
The library is known for well maintained images that make use of best practices. They are automatically rebuild against newer versions of base images and provide other architectures than `amd64` .

https://github.com/docker-library/official-images#contributing-to-the-standard-library
https://github.com/docker-library/official-images/blob/master/NEW-IMAGE-CHECKLIST.md

**Comment by malcyon** [comment]
We don't have any plans to do this. It overcomplicates our release process, and we already have our official image hosted on [Docker Hub](https://hub.docker.com/repository/docker/graylog/graylog).

I am all for best practices, but I think we can implement them without having the image in the standard library.
